import 'package:flutter/material.dart';

List<Map<String, dynamic>> farmacias = [
  {
    'codigo': 1,
    'nombre': 'Farmacia Central',
    'direccion': 'Calle Principal #123',
    'telefono': '123-456-7890',
    'horario': '8:00 AM - 10:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 2,
    'nombre': 'Farmacia del Pueblo',
    'direccion': 'Avenida Independencia #456',
    'telefono': '987-654-3210',
    'horario': '9:00 AM - 9:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 3,
    'nombre': 'Farmacia San José',
    'direccion': 'Calle Comercial #789',
    'telefono': '555-123-4567',
    'horario': '10:00 AM - 8:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 4,
    'nombre': 'Farmacia Esperanza',
    'direccion': 'Avenida Principal #1011',
    'telefono': '111-222-3333',
    'horario': '24 horas',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 5,
    'nombre': 'Farmacia Vida',
    'direccion': 'Calle de la Salud #1213',
    'telefono': '444-555-6666',
    'horario': '7:00 AM - 11:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 6,
    'nombre': 'Farmacia La Estrella',
    'direccion': 'Avenida de la Paz #789',
    'telefono': '999-888-7777',
    'horario': '8:00 AM - 9:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 7,
    'nombre': 'Farmacia Popular',
    'direccion': 'Calle del Sol #555',
    'telefono': '666-777-8888',
    'horario': '10:00 AM - 7:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 8,
    'nombre': 'Farmacia Saludable',
    'direccion': 'Calle de la Luna #321',
    'telefono': '333-444-5555',
    'horario': '9:00 AM - 8:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 9,
    'nombre': 'Farmacia Natura',
    'direccion': 'Avenida Central #777',
    'telefono': '222-333-4444',
    'horario': '8:00 AM - 10:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
  {
    'codigo': 10,
    'nombre': 'Farmacia Bienestar',
    'direccion': 'Calle de los Ángeles #999',
    'telefono': '777-888-9999',
    'horario': '9:00 AM - 9:00 PM',
    'icono': const Icon(Icons.local_pharmacy),
  },
];

